library(data.table)
d <- fread("c:/ProjectTEDGWAS/TrackA_MR/data/eqtl_TSHR_all.csv")
cat("Columns in eqtl_TSHR_all.csv:\n")
print(colnames(d))
cat("\nRange of SNPPos:\n")
print(range(d$SNPPos))
cat("\nNumber of rows:\n")
print(nrow(d))
cat("\nNumber of rows for GeneSymbol TSHR:\n")
print(nrow(d[GeneSymbol == "TSHR"]))
