metadata <- readRDS("C:/ProjectTEDGWAS/TrackA_MR/GEO_validation/GSE105149_metadata.rds")
sink("rds_summary.txt")
cat("=== Column names ===\n")
print(colnames(metadata))
cat("\n=== Table of group ===\n")
print(table(metadata$group, useNA="ifany"))
cat("\n=== Table of diagnosis ===\n")
print(table(metadata$diagnosis, useNA="ifany"))
cat("\n=== First few rows ===\n")
print(head(metadata))
sink()
cat("Done rds check!\n")
